### PR TITLE
updated for rails/master and ruby 2.7

### LINKED ISSUE #34: Deprecation warning with ruby 2.7.1
It looks like the validator raises a warning in 2.7.1.

gems/ruby-2.7.1/gems/strong_password-0.0.9/lib/active_model/validations/password_strength_validator.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

### PR DESCRIPTION
**Pull request by flarecriteria**
Fixes #34

### CODE REVIEW

**Review by omnikron — APPROVED** [review]
Any chance of getting this merged?

**Comment by tsrivishnu** [comment]
Would like to see this merged.

**Comment by dvandersluis** [comment]
👍 Can this be merged and released?

**Comment by bdmac** [comment]
Thanks for the PR and sorry for the delay. `0.0.10` has been released to RubyGems.

**Comment by dvandersluis** [comment]
Thank you! 🙌

**Review by Rad211 — COMMENTED** [review]
Nu înțeleg nimic

**Pull request merged**
