### PR TITLE
Update dictionary_adjuster.rb

### PR DESCRIPTION
**Pull request by thandang**
I just want to add a custom text to dictionary.
By the way I could not use extra_words, I don't know why

### CODE REVIEW

**Comment by bdmac** [comment]
The key is `extra_dictionary_words`. Can you provide any additional information on why you could not use it?

**Comment by thandang** [comment]
Dear bdmac,

Actually I use this key: extra_dictionary_words
I just want to use my custom dictionary to avoid these words in my password. Then I only use this feature:

validates :password, password_strength: {extra_dictionary_words: :my_extra_words, use_dictionary: true}

My extra words is:

def my_extra_words
   ['user', 'admin', 'administrator', 'guest', self.first_name, self.last_name]
end

I thought it will be added into dictionary adjuster to against words in password. But it doesn't

I tried with password: 
+ 'administrator@retT123' but it passed -> wouldn't my expected. 
+ 'userTEW@123' it failed -> it's my expected. I think because 'user' is already included dictionary adjuster

Maybe I wrongly understand. Please help me to know how it works.

Kindly regards,
Than Dang.

**Comment by bdmac** [comment]
The way the dictionary checks work is they do not explicitly ban passwords containing those words. Instead it basically removes the dictionary words from the password when calculating the entropy. In your example, '@retT123' is basically what is used to calculate the entropy which is not a terrible password.

I suspect that the validation _did_ account for your extra words just not in the way you expected.

**Comment by thandang** [comment]
You're completely right.
But, I mean if my password contain 'administrator' then it have to validated as failed like contain 'user'.
Because both of them in extra_dictionary_words
I tried with:
'administratorWEQ@123' -> pass
'userWEQ@123' -> failed

So the way to check is base on calculating the entropy, right?

**Comment by bdmac** [comment]
Yes and I would expect both of those last examples to either pass or fail together. I'll take a closer look in the morning.

**Comment by bdmac** [comment]
I added some specs here to cover your exact use-case and am unable to reproduce the problem you describe. https://github.com/bdmac/strong_password/pull/6/files

As far as I can tell `extra_dictionary_words` works as intended. If you can provide a failing spec then I can investigate further.

**Pull request closed without merging**
